[".config/alacritty/themes"]
type = "git-repo"
url = "https://github.com/alacritty/alacritty-theme"
exact = true
[".asdf"]
type = "git-repo"
url = "https://github.com/asdf-vm/asdf.git"
clone.args = ["--branch", "v0.14.1"]
